-- REIT Golf Day Auction
-- Run this entire script in Supabase > SQL Editor.

create table if not exists public.auction_bids (
  id bigint generated by default as identity primary key,
  bidder_name text not null check (char_length(trim(bidder_name)) between 1 and 100),
  bidder_email text not null check (char_length(trim(bidder_email)) between 3 and 200),
  bid_amount numeric(12,2) not null check (bid_amount > 0),
  created_at timestamptz not null default now()
);

create index if not exists auction_bids_amount_idx
  on public.auction_bids (bid_amount desc, created_at asc);

alter table public.auction_bids enable row level security;

-- Public users cannot read names/emails.
drop policy if exists "Public cannot read auction bids" on public.auction_bids;
create policy "Public cannot read auction bids"
on public.auction_bids
for select
to anon
using (false);

-- Authenticated admin users can read all bids.
drop policy if exists "Authenticated admins can read bids" on public.auction_bids;
create policy "Authenticated admins can read bids"
on public.auction_bids
for select
to authenticated
using (true);

-- Public status exposes only the highest dollar amount.
create or replace view public.auction_public_status
with (security_invoker = false)
as
select coalesce(max(bid_amount), 0)::numeric as highest_bid
from public.auction_bids;

grant select on public.auction_public_status to anon, authenticated;

-- Atomic bid placement. This prevents two simultaneous bidders from
-- both believing they are the valid highest bidder.
create or replace function public.place_auction_bid(
  p_bidder_name text,
  p_bidder_email text,
  p_bid_amount numeric
)
returns table (
  accepted boolean,
  highest_bid numeric,
  minimum_next_bid numeric,
  message text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_highest numeric;
  v_starting_bid numeric := 100;
  v_increment numeric := 50;
  v_close timestamptz := '2026-10-16T17:00:00+11:00';
  v_required numeric;
begin
  -- Lock the table for the short transaction so concurrent bids are evaluated in order.
  lock table public.auction_bids in share row exclusive mode;

  if now() >= v_close then
    select coalesce(max(bid_amount), 0) into v_highest from public.auction_bids;
    return query select false, v_highest, null::numeric, 'This auction has closed.'::text;
    return;
  end if;

  select coalesce(max(bid_amount), 0) into v_highest
  from public.auction_bids;

  if v_highest > 0 then
    v_required := v_highest + v_increment;
  else
    v_required := v_starting_bid;
  end if;

  if p_bidder_name is null or char_length(trim(p_bidder_name)) < 1 then
    return query select false, v_highest, v_required, 'Please enter your name.'::text;
    return;
  end if;

  if p_bidder_email is null or position('@' in p_bidder_email) < 2 then
    return query select false, v_highest, v_required, 'Please enter a valid email address.'::text;
    return;
  end if;

  if p_bid_amount is null or p_bid_amount < v_required then
    return query select false, v_highest, v_required,
      format('Minimum next bid is $%s.', trim(to_char(v_required, 'FM999999999990')))::text;
    return;
  end if;

  insert into public.auction_bids (bidder_name, bidder_email, bid_amount)
  values (trim(p_bidder_name), lower(trim(p_bidder_email)), p_bid_amount);

  return query select true, p_bid_amount, p_bid_amount + v_increment, 'Bid accepted.'::text;
end;
$$;

revoke all on function public.place_auction_bid(text, text, numeric) from public;
grant execute on function public.place_auction_bid(text, text, numeric) to anon, authenticated;

-- Realtime publication, if not already present.
do $$
begin
  alter publication supabase_realtime add table public.auction_bids;
exception
  when duplicate_object then null;
end $$;
